import 'package:flutter/material.dart';

extension ColorResources on BuildContext {
  bool get _isDark => Theme.of(this).brightness == Brightness.dark;
  ColorScheme get _scheme => Theme.of(this).colorScheme;

  Color get primary => _scheme.primary;
  Color get onPrimary => _scheme.onPrimary;
  Color get primaryContainer => _scheme.primaryContainer;
  Color get onPrimaryContainer => _scheme.onPrimaryContainer;
  Color get primaryLight => _scheme.primaryFixed;
  Color get onPrimaryLight => _scheme.onPrimaryFixed;
  Color get secondary => _scheme.secondary;
  Color get tertiary => _scheme.tertiary;
  Color get tertiaryContainer => _scheme.tertiaryContainer;
  Color get error => _scheme.error;
  Color get onError => _scheme.onError;
  Color get errorContainer => _scheme.errorContainer;
  Color get onErrorContainer => _scheme.onErrorContainer;
  Color get surface => _scheme.surface;
  Color get onSurface => _scheme.onSurface;
  Color get surfaceContainerLowest => _scheme.surfaceContainerLowest;
  Color get surfaceContainerLow => _scheme.surfaceContainerLow;
  Color get surfaceContainer => _scheme.surfaceContainer;
  Color get surfaceContainerHigh => _scheme.surfaceContainerHigh;
  Color get surfaceContainerHighest => _scheme.surfaceContainerHighest;
  Color get surfaceVariant => _scheme.surfaceVariant;
  Color get onSurfaceVariant => _scheme.onSurfaceVariant;
  Color get outline => _scheme.outline;
  Color get outlineVariant => _scheme.outlineVariant;
  Color get shadow => _scheme.shadow;
  Color get scrim => _scheme.scrim;

  Color get bgNeutralDefault => _isDark ? const Color(0xFF949494) : const Color(0xFF242424);
  Color get bgNeutralMedium => _isDark ? const Color(0xFF303030) : const Color(0xFFCDCDCD);
  Color get bgNeutralLight => _isDark ? const Color(0xFF303030) : const Color(0xFFE3E3E3);
  Color get bgSuccessDefault => _isDark ? const Color(0xFF1F8A4C) : const Color(0xFF14AE5C);
  Color get bgSuccessMedium => _isDark ? const Color(0xFF1E4A30) : const Color(0xFFCFF7D3);
  Color get bgSuccessLight => _isDark ? const Color(0xFF16311F) : const Color(0xFFEBFFEE);
  Color get bgWarningDefault => _isDark ? const Color(0xFFE5A000) : const Color(0xFFE5A000);
  Color get bgWarningMedium => _isDark ? const Color(0xFF4D3A12) : const Color(0xFFFFF1C2);
  Color get bgWarningLight => _isDark ? const Color(0xFF332608) : const Color(0xFFFFFBEB);
  Color get bgInfoDefault => _isDark ? const Color(0xFFE1EBFA) : const Color(0xFF3979E0);
  Color get bgInfoMedium => _isDark ? const Color(0xFF224A8A) : const Color(0xFFDBE9FF);
  Color get bgInfoLight => _isDark ? const Color(0xFF183057) : const Color(0xFFF1F6FD);
  Color get bgErrorLight => _isDark ? const Color(0xFF3D1210) : const Color(0xFFFEE9E7);
  Color get bgUtilBlanket => _isDark ? const Color(0x3d000000) : const Color(0xb2000000);

  Color get iconBaseDefault => _isDark ? const Color(0xFFFFFFFF) : const Color(0xFF1E1E1E);
  Color get iconBaseMedium => _isDark ? const Color(0xFFB0B0B0) : const Color(0xFF6E6E6E);
  Color get iconBaseLight => _isDark ? const Color(0xFF8A8A8A) : const Color(0xFFBDBDBD);
  Color get iconDisabledDefault => _isDark ? const Color(0xFF6E6E6E) : const Color(0xFFA3A3A3);
  Color get iconNeutralDefault => _isDark ? const Color(0xFFFFFFFF) : const Color(0xFF1E1E1E);
  Color get iconNeutralMedium => _isDark ? const Color(0xFFC7C7C7) : const Color(0xFF4D4D4D);
  Color get iconNeutralLight => _isDark ? const Color(0xFF9E9E9E) : const Color(0xFF9E9E9E);
  Color get iconNeutralOn => _isDark ? const Color(0xff242424) : const Color(0xffFFFFFF);
  Color get iconSuccessDefault => _isDark ? const Color(0xFFA8F0BE) : const Color(0xFF1B7A3D);
  Color get iconSuccessMedium => _isDark ? const Color(0xFF5FD98A) : const Color(0xFF3FAE63);
  Color get iconSuccessLight => _isDark ? const Color(0xFF2FA860) : const Color(0xFF8FD8A3);
  Color get iconSuccessOn => _isDark ? const Color(0xffEBFFEE) : const Color(0xffFFFFFF);
  Color get iconWarningDefault => _isDark ? const Color(0xFFFCE29B) : const Color(0xFF7A3B00);
  Color get iconWarningMedium => _isDark ? const Color(0xFFE5A000) : const Color(0xFFB35900);
  Color get iconWarningLight => _isDark ? const Color(0xFF8A5A1E) : const Color(0xFFF2A93B);
  Color get iconWarningOn => _isDark ? const Color(0xff401B01) : const Color(0xffFFFFFF);
  Color get iconInfoDefault => _isDark ? const Color(0xffDBE9FF) : const Color(0xff224A8A);
  Color get iconInfoMedium => _isDark ? const Color(0xff3979E0) : const Color(0xff3979E0);
  Color get iconInfoLight => _isDark ? const Color(0xff224A8A) : const Color(0xffB2CAF1);
  Color get iconInfoOn => _isDark ? const Color(0xff15253F) : const Color(0xffFFFFFF);
  Color get iconDangerDefault => _isDark ? const Color(0xFFFFB3B0) : const Color(0xFF7A0000);
  Color get iconDangerMedium => _isDark ? const Color(0xFFEF5350) : const Color(0xFFC0392B);
  Color get iconDangerLight => _isDark ? const Color(0xFFC00F0C) : const Color(0xFFEC221F);
  Color get iconDangerOn => _isDark ? const Color(0xffFEE9E7) : const Color(0xffFFFFFF);

  Color get textBaseDefault => _isDark ? const Color(0xFFFFFFFF) : const Color(0xFF1E1E1E);
  Color get textBaseMedium => _isDark ? const Color(0xFFC7C7C7) : const Color(0xFF757575);
  Color get textBaseLight => _isDark ? const Color(0xFF9E9E9E) : const Color(0xFFA3A3A3);
  Color get textNeutralDefault => _isDark ? const Color(0xFFFFFFFF) : const Color(0xFF1E1E1E);
  Color get textNeutralMedium => _isDark ? const Color(0xFFC7C7C7) : const Color(0xFF6E6E6E);
  Color get textNeutralLight => _isDark ? const Color(0xFF9E9E9E) : const Color(0xFF9E9E9E);
  Color get textNeutralOn => _isDark ? const Color(0xff242424) : const Color(0xffFFFFFF);
  Color get textDangerDefault => _isDark ? const Color(0xFFFFB3B0) : const Color(0xFF7A0000);
  Color get textDangerMedium => _isDark ? const Color(0xFFEF5350) : const Color(0xFFC0392B);
  Color get textDangerLight => _isDark ? const Color(0xFFC00F0C) : const Color(0xFFEC221F);
  Color get textDangerOn => _isDark ? const Color(0xff300603) : const Color(0xffFFFFFF);
  Color get textWarningDefault => _isDark ? const Color(0xFFFCE29B) : const Color(0xFF7A3B00);
  Color get textWarningMedium => _isDark ? const Color(0xFFE5A000) : const Color(0xFFB35900);
  Color get textWarningLight => _isDark ? const Color(0xFF8A5A1E) : const Color(0xFFF2A93B);
  Color get textWarningOn => _isDark ? const Color(0xff300603) : const Color(0xffFFFFFF);
  Color get textInfoDefault => _isDark ? const Color(0xffE1EBFA) : const Color(0xff2A61BA);
  Color get textInfosMedium => _isDark ? const Color(0xFFB2CAF1) : const Color(0xFF3979E0);
  Color get textInfoLight => _isDark ? const Color(0xFF6BA4FF) : const Color(0xFF6BA4FF);
  Color get textInfoOn => _isDark ? const Color(0xff15253F) : const Color(0xffFFFFFF);
  Color get textSuccessDefault => _isDark ? const Color(0xFFA8F0BE) : const Color(0xFF1B7A3D);
  Color get textSuccessMedium => _isDark ? const Color(0xFF5FD98A) : const Color(0xFF3FAE63);
  Color get textSuccessLight => _isDark ? const Color(0xFF2FA860) : const Color(0xFF8FD8A3);
  Color get textSuccessOn => _isDark ? const Color(0xff062D1B) : const Color(0xffFFFFFF);
}
